# CloudFormation output name: `sls-${SERVICE_NAME}-${STAGE}`
service: sls-${self:custom.service}

package:
  individually: true

custom:
  service: ${env:SERVICE_NAME}
  region: ${opt:region, env:AWS_REGION}
  stage: ${opt:stage, env:STAGE}
  jetpack:
    preInclude:
      - "!**" # Start with no files at all.
    trace:
      # Use trace mode for speed and ignore aws-sdk + all deps
      ignores:
        - "aws-sdk"
        - "critters"
      allowMissing:
        # TODO: Add to trace-dep
        # "./.next/serverless/pages/index.js":
        #   - "critters" # For CSS optimization
        "node-fetch":
          - "encoding"
      # TODO: RESOLUTIONS
      dynamic:
        resolutions:
          # [169:22]: require(`./transformers/${Transformer}.js`)
          "@ampproject/toolbox-optimizer/lib/DomTransformer.js": []

plugins:
  - serverless-jetpack
  - serverless-offline

provider:
  name: aws

  # Required: import the default role that terraform-aws-serverless generates.
  role:
    Fn::ImportValue: tf-${self:custom.service}-${self:custom.stage}-LambdaExecutionRoleArn

  # Lambda configuration
  runtime: nodejs12.x
  timeout: 30 # seconds (`300` max)
  memorySize: 128 # MB value (`1024` default)

  # Deployment / environment configuration
  region: ${self:custom.region}
  stage: ${self:custom.stage}
  environment:
    STAGE: ${self:custom.stage}
    SERVICE_NAME: ${self:custom.service}

  # AWS Resource Tags: Match terraform module
  stackTags: # For CF stack
    Stage: ${self:custom.stage}
    Service: ${self:custom.service}
  tags: # For resources
    Stage: ${self:custom.stage}
    Service: ${self:custom.service}

functions:
  # SCENARIO - base: The simplest, vanilla Serverless app.
  blog:
    handler: server/index.handler
    events: # Use a generic proxy to allow Express app to route.
      - http: ANY /blog
      - http: 'ANY /blog/{proxy+}'
    package:
      include:
        # Raw data for posts is read from disk outside `.next` build directory.
        - "posts/**/*.md"
        # Static assets.
        # TODO(STATIC): Add a note about this.
        - ".next/static/**"
